name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using sshkey
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_ZERO }}
        username: ${{ secrets.USERNAME_ZERO }}
        key: ${{ secrets.PRIVATEKEY_ZERO }}
        port: ${{ secrets.PORT_ZERO }}
        script: python3 ~/lights/update_lights.py ${{ secrets.AOC_SESSION }} ${{ secrets.USERNAME_AOC }} ${{ secrets.USERNAME_AOC }}
