name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using sshkey
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_ZERO }}
        username: ${{ secrets.USERNAME_ZERO }}
        key: ${{ secrets.PRIVATEKEY_ZERO }}
        port: ${{ secrets.PORT_ZERO }}
        script: |
            cd ~/AoC/AoC_private
            git pull
            sudo python3 ~/AoC/AoC_private/update_lights.py herobrauni